/**
 * Registry codegen — the mechanism that makes series/**\/*.yaml (and,
 * alongside it, datasets/**\/*.yaml) the single source of truth for
 * citation semantics (PLAN.md §4). Reads every file, validates against the
 * matching JSON Schema, then emits:
 *
 *   packages/registry/src/generated/series.gen.ts    TS types, SERIES lookup,
 *                                                     citation + guard helpers
 *   packages/registry/src/generated/datasets.gen.ts  TS types, DATASETS
 *                                                     lookup, citation helper
 *
 * `series` is for a single numeric value per period (joined against
 * `observation`); `datasets` is for data that reaches a page as full rows
 * with many columns (e.g. one auction event) rather than one value per
 * period — it carries only a citation, no unit/magnitude/accounting_concept.
 * Both are "a number/row may only reach a page through a registry id"
 * mechanisms; pick whichever matches the shape of what's being cited.
 *
 * Never hand-edit either generated file. Run `pnpm gen` after any YAML
 * change. CI runs `pnpm gen` and fails the build on a resulting git diff
 * (drift).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, globSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { Ajv2020 } from "ajv/dist/2020.js";
import addFormatsModule from "ajv-formats";

// ajv-formats ships CJS; under NodeNext ESM interop the callable may sit on
// .default at runtime while the namespace type is non-callable — normalize.
type AddFormatsFn = (ajv: InstanceType<typeof Ajv2020>) => unknown;
const _afm = addFormatsModule as unknown as AddFormatsFn & { default?: AddFormatsFn };
const addFormats: AddFormatsFn = _afm.default ?? _afm;

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..", "..");
const REGISTRY = join(HERE, "..");
const CHECK = process.argv.includes("--check");

// ---------- types mirroring schema/series.schema.json ----------

interface RevisionPolicy {
  status?: "provisional" | "final" | "mixed";
  note?: string;
}

interface NotComparableEdge {
  series: string;
  reason: string;
}

interface Series {
  id: string;
  label: string;
  definition: string;
  aliases?: string[];
  agency: string;
  dataset: string;
  dataset_url: string;
  unit: "usd" | "index_point" | "persons" | "households";
  magnitude: "ones" | "thousands" | "millions" | "billions";
  accounting_concept:
    | "receipt"
    | "outlay"
    | "deficit"
    | "debt"
    | "balance"
    | "interest"
    | "price_index"
    | "projection"
    | "population"
    | "households";
  cadence: "daily" | "weekly" | "monthly" | "annual";
  citation: string;
  revision_policy?: RevisionPolicy;
  notes?: string[];
  not_comparable_with?: NotComparableEdge[];
}

// ---------- load + validate ----------

const schema = JSON.parse(
  readFileSync(join(REGISTRY, "schema", "series.schema.json"), "utf8"),
);
const ajv = new Ajv2020({ allErrors: true, allowUnionTypes: true });
addFormats(ajv);
const validate = ajv.compile(schema);

const files = globSync(join(REGISTRY, "series", "**", "*.yaml")).sort();
if (files.length === 0) throw new Error("No series YAML files found under packages/registry/series/");

const seriesList: Series[] = [];
const errors: string[] = [];
for (const f of files) {
  const doc = parse(readFileSync(f, "utf8")) as Series;
  if (!validate(doc)) {
    errors.push(
      `${relative(ROOT, f)}:\n` +
        (validate.errors ?? [])
          .map((e) => `   ${e.instancePath || "$"}: ${e.message}`)
          .join("\n"),
    );
    continue;
  }
  seriesList.push(doc);
}
if (errors.length) {
  console.error(`Schema validation failed for ${errors.length} file(s):\n${errors.join("\n")}`);
  process.exit(1);
}

// Cross-file integrity: unique ids; not_comparable_with targets must exist.
const ids = new Set<string>();
for (const s of seriesList) {
  if (ids.has(s.id)) {
    console.error(`Duplicate series id: ${s.id}`);
    process.exit(1);
  }
  ids.add(s.id);
}
const danglingEdges: string[] = [];
for (const s of seriesList) {
  for (const edge of s.not_comparable_with ?? []) {
    if (!ids.has(edge.series)) danglingEdges.push(`${s.id} -> ${edge.series}`);
  }
}
if (danglingEdges.length) {
  console.error(`not_comparable_with references unknown series id(s):\n   ${danglingEdges.join("\n   ")}`);
  process.exit(1);
}

seriesList.sort((a, b) => a.id.localeCompare(b.id));

// ---------- emit ----------

const bannerFor = (sourceGlob: string) =>
  "// GENERATED by packages/registry/codegen/generate.ts — DO NOT EDIT.\n" +
  `// Source of truth: packages/registry/${sourceGlob}. Run \`pnpm gen\`.\n`;
const banner = bannerFor("series/**/*.yaml");

const tsUnion = (values: string[]) => values.map((v) => JSON.stringify(v)).join(" | ");

const ts = `${banner}
export type Unit = ${tsUnion(schema.properties.unit.enum)};
export type Magnitude = ${tsUnion(schema.properties.magnitude.enum)};
export type AccountingConcept = ${tsUnion(schema.properties.accounting_concept.enum)};
export type Cadence = ${tsUnion(schema.properties.cadence.enum)};
export type RevisionStatus = ${tsUnion(schema.properties.revision_policy.properties.status.enum)};

export interface SeriesDef {
  readonly id: string;
  readonly label: string;
  readonly definition: string;
  readonly aliases: readonly string[];
  readonly agency: string;
  readonly dataset: string;
  readonly datasetUrl: string;
  readonly unit: Unit;
  readonly magnitude: Magnitude;
  readonly accountingConcept: AccountingConcept;
  readonly cadence: Cadence;
  readonly citation: string;
  readonly revisionStatus?: RevisionStatus;
  readonly revisionNote?: string;
  readonly notes: readonly string[];
  readonly notComparableWith: readonly { readonly series: string; readonly reason: string }[];
}

export type SeriesId = ${tsUnion(seriesList.map((s) => s.id))};

export const SERIES: Record<SeriesId, SeriesDef> = {
${seriesList
  .map((s) => {
    const def: Record<string, unknown> = {
      id: s.id,
      label: s.label,
      definition: s.definition.trim(),
      aliases: s.aliases ?? [],
      agency: s.agency,
      dataset: s.dataset,
      datasetUrl: s.dataset_url,
      unit: s.unit,
      magnitude: s.magnitude,
      accountingConcept: s.accounting_concept,
      cadence: s.cadence,
      citation: s.citation.trim(),
      revisionStatus: s.revision_policy?.status,
      revisionNote: s.revision_policy?.note?.trim(),
      notes: (s.notes ?? []).map((n) => n.trim()),
      notComparableWith: (s.not_comparable_with ?? []).map((e) => ({ series: e.series, reason: e.reason.trim() })),
    };
    return `  ${JSON.stringify(s.id)}: ${JSON.stringify(def, null, 2).replace(/\n/g, "\n  ")},`;
  })
  .join("\n")}
};

/** All series ids, sorted. */
export const SERIES_IDS: readonly SeriesId[] = Object.keys(SERIES).sort() as SeriesId[];

/** Lookup by id. Returns undefined for an unknown id — callers decide how to render "unknown series" rather than this module guessing. */
export function getSeries(id: string): SeriesDef | undefined {
  return (SERIES as Record<string, SeriesDef>)[id];
}

/**
 * Full citation text for a series, with {access_date} substituted.
 * Defaults to today (UTC) in YYYY-MM-DD form when accessDate is omitted.
 */
export function citationFor(id: SeriesId, accessDate?: string): string {
  const def = SERIES[id];
  const date = accessDate ?? new Date().toISOString().slice(0, 10);
  return def.citation.replaceAll("{access_date}", date);
}

/**
 * Guard: series whose accounting concepts differ may not be summed or
 * directly compared (CLAUDE.md hard rule). Returns the declared
 * human-readable reason when the pair is explicitly marked incomparable, a
 * generic concept-mismatch reason otherwise; null when combining is allowed
 * (same series, or same accounting_concept with no declared edge).
 */
export function incomparabilityReason(a: SeriesId, b: SeriesId): string | null {
  if (a === b) return null;
  const sa = SERIES[a];
  const sb = SERIES[b];
  const declared =
    sa.notComparableWith.find((e) => e.series === b) ??
    sb.notComparableWith.find((e) => e.series === a);
  if (declared) return declared.reason;
  if (sa.accountingConcept !== sb.accountingConcept) {
    return \`Different accounting concepts: \${sa.accountingConcept} vs \${sb.accountingConcept}. Combining them requires a declared bridge.\`;
  }
  if (sa.magnitude !== sb.magnitude) {
    return \`Different published magnitudes: \${sa.magnitude} vs \${sb.magnitude}. Convert at the presentation boundary before combining, never in storage.\`;
  }
  return null;
}
`;

/** Shared by every generated-file emission below: write in normal mode, or diff-and-fail in `--check` mode (CI's drift gate). */
function emitOrCheck(outPath: string, contents: string, itemLabel: string, itemCount: number): void {
  if (CHECK) {
    const existing = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
    if (existing !== contents) {
      console.error(`DRIFT: ${relative(ROOT, outPath)} is stale — run \`pnpm gen\``);
      process.exit(1);
    }
    console.log(`checked ${relative(ROOT, outPath)} against ${itemCount} ${itemLabel} (no drift)`);
  } else {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, contents);
    console.log(`wrote ${relative(ROOT, outPath)} from ${itemCount} ${itemLabel}`);
  }
}

emitOrCheck(join(REGISTRY, "src", "generated", "series.gen.ts"), ts, "series", seriesList.length);

// ---------- datasets/**/*.yaml -> datasets.gen.ts ----------
// Same mechanism as series above, but for citation-only dataset entries —
// see this file's module doc comment for when to use which.

interface Dataset {
  id: string;
  label: string;
  aliases?: string[];
  agency: string;
  dataset: string;
  dataset_url: string;
  citation: string;
  notes?: string[];
}

const datasetSchema = JSON.parse(readFileSync(join(REGISTRY, "schema", "dataset.schema.json"), "utf8"));
const validateDataset = ajv.compile(datasetSchema);

const datasetFiles = globSync(join(REGISTRY, "datasets", "**", "*.yaml")).sort();
if (datasetFiles.length === 0) throw new Error("No dataset YAML files found under packages/registry/datasets/");

const datasetList: Dataset[] = [];
const datasetErrors: string[] = [];
for (const f of datasetFiles) {
  const doc = parse(readFileSync(f, "utf8")) as Dataset;
  if (!validateDataset(doc)) {
    datasetErrors.push(
      `${relative(ROOT, f)}:\n` +
        (validateDataset.errors ?? [])
          .map((e) => `   ${e.instancePath || "$"}: ${e.message}`)
          .join("\n"),
    );
    continue;
  }
  datasetList.push(doc);
}
if (datasetErrors.length) {
  console.error(`Schema validation failed for ${datasetErrors.length} dataset file(s):\n${datasetErrors.join("\n")}`);
  process.exit(1);
}

const datasetIds = new Set<string>();
for (const d of datasetList) {
  if (datasetIds.has(d.id)) {
    console.error(`Duplicate dataset id: ${d.id}`);
    process.exit(1);
  }
  datasetIds.add(d.id);
}

datasetList.sort((a, b) => a.id.localeCompare(b.id));

const datasetsTs = `${bannerFor("datasets/**/*.yaml")}
export interface DatasetDef {
  readonly id: string;
  readonly label: string;
  readonly aliases: readonly string[];
  readonly agency: string;
  readonly dataset: string;
  readonly datasetUrl: string;
  readonly citation: string;
  readonly notes: readonly string[];
}

export type DatasetId = ${tsUnion(datasetList.map((d) => d.id))};

export const DATASETS: Record<DatasetId, DatasetDef> = {
${datasetList
  .map((d) => {
    const def: Record<string, unknown> = {
      id: d.id,
      label: d.label,
      aliases: d.aliases ?? [],
      agency: d.agency,
      dataset: d.dataset,
      datasetUrl: d.dataset_url,
      citation: d.citation.trim(),
      notes: (d.notes ?? []).map((n) => n.trim()),
    };
    return `  ${JSON.stringify(d.id)}: ${JSON.stringify(def, null, 2).replace(/\n/g, "\n  ")},`;
  })
  .join("\n")}
};

/** All dataset ids, sorted. */
export const DATASET_IDS: readonly DatasetId[] = Object.keys(DATASETS).sort() as DatasetId[];

/** Lookup by id. Returns undefined for an unknown id — callers decide how to render "unknown dataset" rather than this module guessing. */
export function getDataset(id: string): DatasetDef | undefined {
  return (DATASETS as Record<string, DatasetDef>)[id];
}

/**
 * Full citation text for a dataset, with {access_date} substituted.
 * Defaults to today (UTC) in YYYY-MM-DD form when accessDate is omitted.
 */
export function datasetCitationFor(id: DatasetId, accessDate?: string): string {
  const def = DATASETS[id];
  const date = accessDate ?? new Date().toISOString().slice(0, 10);
  return def.citation.replaceAll("{access_date}", date);
}
`;

emitOrCheck(join(REGISTRY, "src", "generated", "datasets.gen.ts"), datasetsTs, "dataset(s)", datasetList.length);
